# Generated by Django 5.0.1 on 2024-03-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='currentStudent',
        ),
    ]
